version: "3.7"
services:
  mysql:
    image: mysql:8.0.30
    ports:
      - '3306:3306'
    volumes:
      - ./MySql/data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./PostgresSql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
      - POSTGRES_USER=app

  gate-simulator:
    build: .
    image: gate-simulator:1.0
    ports:
      - '9999:9999'